Validation
dokspy/buy-books pull request #5
Opened 2023-05-26 19:23 UTC by dokspy

Короч, тут ще пахать і пахать, і да я знаю що не всі console.log удалали

2023-05-27 13:42 UTC, amarsik1 requested changes

2023-05-27 13:56 UTC, volodya7292 approved these changes

2023-05-27 14:04 UTC, volodya7292 reviewed
Looks terrible

2023-05-29 15:10 UTC, amarsik1 approved these changes

2023-06-06 14:31 UTC, merged